### PR TITLE
fix(config): ensure compatible case with nr1

### LINKED ISSUE #120: profile uses inconsistent casing for API: adminAPIKey, apiKey
### Objective
Clean up the variable casing here.  Maintain compatibility with `nr1`.

### PR DESCRIPTION
**Pull request by SowmyaJujjuri**
Resolved #120

### CODE REVIEW

File: internal/config/config.go [hunk 1]
```diff
@@ -166,7 +166,7 @@ func (c *Config) Get(key string) {
 // Set sets a config value.
 func (c *Config) Set(key string, value interface{}) error {
 	if !stringInStrings(key, validConfigKeys()) {
-		return fmt.Errorf("\"%s\" is not a valid key; Please use one of: %s", key, validConfigKeys())
+		return fmt.Errorf("\"%s\" is not a valid key; use one of: %s", key, validConfigKeys())
```
Comment (zlesnr) [inline internal/config/config.go:169]: Do we still want to say please here?

File: internal/config/config.go [hunk 2]
```diff
@@ -438,7 +438,7 @@ func validConfigKeys() []string {
 
 func stringInStrings(s string, ss []string) bool {
 	for _, v := range ss {
-		if strings.EqualFold(v, s) {
+		if v == s {
```
Comment (ctrombley) [inline internal/config/config.go:441]: This will enforce case sensitivity when validating keys, which is an effective solution for this issue.  Nice job!

However, `stringInStrings` is also used to [validate the config *values*](https://github.com/newrelic/newrelic-cli/blob/master/internal/config/config.go#L339-L349), so case sensitivity would be enforced when checking a log level the user has chosen.  This is less user friendly - we want them to be able to use "INFO", "info", or "Info" for instance.   

How about introducing a boolean arg similar to [this code](https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/validation/strings.go#L132) that would allow turning case sensitivity on or off depending on the use case?  We could use the case sensitive version to validate the keys, and the case insensitive version to validate the values.

We will also need to update the case of the keys in the [`validate` method](https://github.com/newrelic/newrelic-cli/blob/master/internal/config/config.go#L339-L349) after enforcing case sensitivity, as those case statements will stop evaluating to true.

File: internal/config/config_integration_test.go [hunk 3]
```diff
@@ -22,11 +22,11 @@ func TestConfigSetLogLevel(t *testing.T) {
 
 	// Set the valid log levels
 	for _, l := range []string{
-		"ERROR",
-		"WARN",
-		"INFO",
-		"DEBUG",
-		"TRACE",
+		"Error",
```
Comment (ctrombley) [inline internal/config/config_integration_test.go:25]: See the related comment.  We should still allow the user to use case-insensitive values.

File: internal/config/config.go [hunk 4]
```diff
@@ -27,7 +27,7 @@ const (
 	DefaultEnvPrefix = "newrelic"
 
 	// DefaultLogLevel is the default log level
-	DefaultLogLevel = "INFO"
+	DefaultLogLevel = "Info"
```
Comment (ctrombley) [inline internal/config/config.go:30]: See the related comment.  We should still allow the user to use case-insensitive values.

File: internal/config/config_integration_test.go [hunk 5]
```diff
@@ -35,6 +35,12 @@ func TestConfigSetLogLevel(t *testing.T) {
 
 	err = c.Set("logLevel", "INVALID_VALUE")
 	assert.Error(t, err)
+
+	err = c.Set("loglevel", "Info")
+	assert.Error(t, err)
+
+	err = c.Set("Loglevel", "Debug")
+	assert.Error(t, err)
```
Comment (zlesnr) [inline internal/config/config_integration_test.go:43]: What do you think about also including a couple tests for a `c.Get()` just to ensure that we're getting back what we expect also.  I think that would probably effectively test the round trip here.

File: internal/config/config.go [hunk 6]
```diff
@@ -335,10 +335,11 @@ func (c *Config) setDefaults() error {
 
 func (c *Config) validate() error {
 	err := c.visitAllConfigFields(func(v *Value) error {
+		// switch k := strings.ToLower(v.Name); k {
```
Comment (ctrombley) [inline internal/config/config.go:338]: Can this be removed?
