### PR TITLE
tests(config): fix tests that were overriding actual config files

### LINKED ISSUE #99: Config integration tests overwrites user config.yml
### Description
When running tests locally / local dev environment, the config integration tests is overwriting the user config.  Looking at the test, it appears to specify a directory to use instead, but it appears not to be functioning.

https://github.com/newrelic/newrelic-cli/blob/master/internal/config/config_integration_test.go

### Go Version
`go version go1.14 darwin/amd64`

### Current behavior
Running the config integration test modifies the user config.yml

### Expected behavior
Tests do not change the user config

### Steps To Reproduce
1. `make test-integration`
2. review ~/.newrelic/config.yml
3. See `logLevel` and `pluginDir` have changed

### PR DESCRIPTION
**Pull request by ctrombley**
Resolves #99 .
 
This PR fixes some internal config logic so that the tests no longer overwrite the actual configuration file.

### CODE REVIEW

File: internal/config/config.go [hunk 1]
```diff
@@ -402,10 +404,8 @@ func readConfig(configDir string) (*viper.Viper, error) {
 	cfgViper.SetEnvPrefix(DefaultEnvPrefix)
 	cfgViper.SetConfigName(DefaultConfigName)
 	cfgViper.SetConfigType(DefaultConfigType)
-	cfgViper.AddConfigPath(configDir)              // adding provided directory as search path
-	cfgViper.AddConfigPath(DefaultConfigDirectory) // adding home directory as search path
```
Comment (jthurman42) [inline internal/config/config.go]: should we search these other paths still? If someone passes in a dir that doesn't exist / is empty, and has a default config would it be an error? Maybe an unexpected success?

Comment (ctrombley) [reply internal/config/config.go]: The problem is that we need a deterministic place to write the file.__
